//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobProject.Service.JobProjectUserServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JobProjectUserServiceReference1.IJobProjectUserService")]
    public interface IJobProjectUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobProjectUserService/Create", ReplyAction="http://tempuri.org/IJobProjectUserService/CreateResponse")]
        void Create(ModelLayer.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobProjectUserService/Create", ReplyAction="http://tempuri.org/IJobProjectUserService/CreateResponse")]
        System.Threading.Tasks.Task CreateAsync(ModelLayer.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobProjectUserService/Delete", ReplyAction="http://tempuri.org/IJobProjectUserService/DeleteResponse")]
        void Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobProjectUserService/Delete", ReplyAction="http://tempuri.org/IJobProjectUserService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobProjectUserService/Get", ReplyAction="http://tempuri.org/IJobProjectUserService/GetResponse")]
        ModelLayer.User Get(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobProjectUserService/Get", ReplyAction="http://tempuri.org/IJobProjectUserService/GetResponse")]
        System.Threading.Tasks.Task<ModelLayer.User> GetAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobProjectUserService/GetAll", ReplyAction="http://tempuri.org/IJobProjectUserService/GetAllResponse")]
        ModelLayer.User[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobProjectUserService/GetAll", ReplyAction="http://tempuri.org/IJobProjectUserService/GetAllResponse")]
        System.Threading.Tasks.Task<ModelLayer.User[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobProjectUserService/Update", ReplyAction="http://tempuri.org/IJobProjectUserService/UpdateResponse")]
        void Update(ModelLayer.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobProjectUserService/Update", ReplyAction="http://tempuri.org/IJobProjectUserService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(ModelLayer.User user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJobProjectUserServiceChannel : JobProject.Service.JobProjectUserServiceReference1.IJobProjectUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JobProjectUserServiceClient : System.ServiceModel.ClientBase<JobProject.Service.JobProjectUserServiceReference1.IJobProjectUserService>, JobProject.Service.JobProjectUserServiceReference1.IJobProjectUserService {
        
        public JobProjectUserServiceClient() {
        }
        
        public JobProjectUserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JobProjectUserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobProjectUserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobProjectUserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Create(ModelLayer.User user) {
            base.Channel.Create(user);
        }
        
        public System.Threading.Tasks.Task CreateAsync(ModelLayer.User user) {
            return base.Channel.CreateAsync(user);
        }
        
        public void Delete(int id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public ModelLayer.User Get(int id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<ModelLayer.User> GetAsync(int id) {
            return base.Channel.GetAsync(id);
        }
        
        public ModelLayer.User[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<ModelLayer.User[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public void Update(ModelLayer.User user) {
            base.Channel.Update(user);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(ModelLayer.User user) {
            return base.Channel.UpdateAsync(user);
        }
    }
}
